linters-settings:
  funlen:
    lines: 200
    statements: 100
    ignore-comments: true
  govet:
    enable-all: true
  nolintlint:
    require-explanation: true
    require-specific: true
  wsl:
    force-err-cuddling: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gomnd:
    ignored-files:
      - "argon2id.go"

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 30s
